spring:
  application:
    name: ecommerce-simulation-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ecommerce_db}
    username: ${DB_USERNAME:ecommerce_user}
    password: ${DB_PASSWORD:ecommerce_pass}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

app:
  jwt:
    # Zorunlu: env variable olarak set edilmeli, burada default değer YOK.
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
